name: Build docker image

on:
  workflow_dispatch:

env:
    REGISTRY: ghcr.io

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup jdk-17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build maven and docker image
        run: |
          ./mvnw clean install -DskipTests
          ./core/docker/build.sh -a amd64

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker images
          TRINO_VERSION=$(./mvnw  -f ./pom.xml --quiet help:evaluate -Dexpression=project.version -DforceStdout)
          echo TRINO_VERSION: $TRINO_VERSION
          IMAGE_TAG=${TRINO_VERSION}-amd64-${GITHUB_RUN_NUMBER}-${GITHUB_SHA::7}
          docker tag trino:$IMAGE_TAG ghcr.io/zettablock/trino-public:$IMAGE_TAG
          docker push ghcr.io/zettablock/trino-public:$IMAGE_TAG
